name: Deploy
on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/test.yml
  deploy:
    name: "Deploy to Remote"
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >>~/.ssh/config <<END
          Host my-vm
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}
        
      - name: Print project root directory
        run: ssh my-vm 'cd ${{ secrets.PROJECT_ROOT }} && pwd'

      - name: Deploy site
        run: ssh my-vm '${{ secrets.PROJECT_ROOT }}/redeploy-site.sh'

      - name: Output Container Status
        run: ssh my-vm 'cd ${{ secrets.PROJECT_ROOT }} && docker-compose ps'

      - name: Notify
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content="🚀 Deployment Successful"
  run-if-fail:
    needs: [deploy]
    if: needs.deploy.result == 'failure'
    steps:
      - name: Notify
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content="🚨 Deployment Failed"